### ISSUE TITLE
Update BKT mastery

### ISSUE THREAD

**Issue by symd** [CAHLR/OATutor#47]
If I want to set a value other than 0.1 to the initial probMastery of a problem, where should I do it? 
In App.js (this.bktparams)?
or
problem.js?
I would like to know whether it will be rewritten after one exercise.

**Comment by zpardos** [comment]
Within the content repo, there's a folder called "bkt-params" that contains a params file that defines all skills' parameter values.

For example, https://github.com/CAHLR/OATutor-Content/blob/3ef9b3f0933cd1e8388a4031a80a853d4047a887/bkt-params/defaultBKTParams.json
